export const images = [
  { uri: require("./components/1.jpg") },
  { uri: require("./components/2.jpg") },
  { uri: require("./components/3.jpg") },
  { uri: require("./components/4.jpg") },
  { uri: require("./components/5.jpg") },
  { uri: require("./components/1.jpg") },
  { uri: require("./components/2.jpg") },
  { uri: require("./components/3.jpg") },
  { uri: require("./components/4.jpg") },
  { uri: require("./components/5.jpg") },
  { uri: require("./components/1.jpg") },
  { uri: require("./components/2.jpg") },
  { uri: require("./components/3.jpg") },
  { uri: require("./components/4.jpg") },
  { uri: require("./components/5.jpg") },
  { uri: require("./components/1.jpg") },
  { uri: require("./components/2.jpg") },
  { uri: require("./components/3.jpg") },
  { uri: require("./components/4.jpg") },
  { uri: require("./components/5.jpg") },
];
